/**
 * Minimal vendor → HQ mapping for the AV products.
 * Only entries verified from public sources are included here.
 * continent is a coarse label for display.
 */

export type AvVendor = {
  product: string;
  company?: string;
  city: string;
  country: string;
  continent: "America" | "Asia" | "Europe" | "Pacific";
  timezone: string;
};

export const AV_VENDOR_LOCATIONS: AvVendor[] = [
  // EUROPE
  {
    product: "Avast Free Antivirus",
    company: "Avast Software",
    city: "Prague",
    country: "Czechia",
    continent: "Europe",
    timezone: "Europe/Prague",
  },
  {
    product: "AVG Internet Security",
    company: "AVG Technologies",
    city: "Brno",
    country: "Czechia",
    continent: "Europe",
    timezone: "Europe/Prague",
  },
  {
    product: "Bitdefender Endpoint Security",
    company: "Bitdefender",
    city: "Bucharest",
    country: "Romania",
    continent: "Europe",
    timezone: "Europe/Bucharest",
  },
  {
    product: "ESET INTERNET SECURITY",
    company: "ESET",
    city: "Bratislava",
    country: "Slovakia",
    continent: "Europe",
    timezone: "Europe/Bratislava",
  },
  {
    product: "ESET Smart Security Premium",
    company: "ESET",
    city: "Bratislava",
    country: "Slovakia",
    continent: "Europe",
    timezone: "Europe/Bratislava",
  },
  {
    product: "ESET Endpoint Security",
    company: "ESET",
    city: "Bratislava",
    country: "Slovakia",
    continent: "Europe",
    timezone: "Europe/Bratislava",
  },
  {
    product: "G Data ANTIVIRUS",
    company: "G DATA CyberDefense",
    city: "Bochum",
    country: "Germany",
    continent: "Europe",
    timezone: "Europe/Berlin",
  },
  {
    product: "IKARUS anti.virus",
    company: "IKARUS Security Software",
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    timezone: "Europe/Vienna",
  },
  {
    product: "Arcabit AntiVirus",
    company: "Arcabit",
    city: "Warsaw",
    country: "Poland",
    continent: "Europe",
    timezone: "Europe/Warsaw",
  },
  {
    product: "CHOMAR-ES",
    company: "CHOMAR",
    city: "Mersin",
    country: "Türkiye",
    continent: "Europe",
    timezone: "Europe/Istanbul",
  },
  {
    product: "CHOMAR-IS",
    company: "CHOMAR",
    city: "Mersin",
    country: "Türkiye",
    continent: "Europe",
    timezone: "Europe/Istanbul",
  },
  {
    product: "TrustPort ANTIVIRUS SPHERE",
    company: "TrustPort",
    city: "Brno",
    country: "Czechia",
    continent: "Europe",
    timezone: "Europe/Prague",
  },
  {
    product: "Panda Endpoint Protection Plus",
    company: "Panda Security",
    city: "Las Rozas (Madrid)",
    country: "Spain",
    continent: "Europe",
    timezone: "Europe/Madrid",
  },
  {
    product: "Panda Free Antivirus",
    company: "Panda Security",
    city: "Las Rozas (Madrid)",
    country: "Spain",
    continent: "Europe",
    timezone: "Europe/Madrid",
  },
  {
    product: "Tabidus United EndPoint Protection",
    company: "Tabidus Technology",
    city: "Vienna",
    country: "Austria",
    continent: "Europe",
    timezone: "Europe/Vienna",
  },
  {
    product: "TeamViewer ITbrain Anti-Malware",
    company: "TeamViewer",
    city: "Göppingen",
    country: "Germany",
    continent: "Europe",
    timezone: "Europe/Berlin",
  },
  {
    product: "Zemana Endpoint Security",
    company: "Zemana",
    city: "Sarajevo",
    country: "Bosnia and Herzegovina",
    continent: "Europe",
    timezone: "Europe/Sarajevo",
  },
  {
    product: "Surfshark Antivirus",
    company: "Surfshark B.V.",
    city: "Amsterdam",
    country: "Netherlands",
    continent: "Europe",
    timezone: "Europe/Amsterdam",
  },
  {
    product: "Acronis True Image 2021",
    company: "Acronis",
    city: "Schaffhausen",
    country: "Switzerland",
    continent: "Europe",
    timezone: "Europe/Zurich",
  },
  {
    product: "Acronis Total Protect",
    company: "Acronis",
    city: "Schaffhausen",
    country: "Switzerland",
    continent: "Europe",
    timezone: "Europe/Zurich",
  },

  // ISRAEL (ASIA - JERUSALEM)
  {
    product: "Coronet",
    company: "Coro Cybersecurity",
    city: "Tel Aviv–Yafo / Ramat Gan",
    country: "Israel",
    continent: "Asia",
    timezone: "Asia/Jerusalem",
  },
  {
    product: "Cynet",
    company: "Cynet Security",
    city: "Tel Aviv–Yafo",
    country: "Israel",
    continent: "Asia",
    timezone: "Asia/Jerusalem",
  },
  {
    product: "Cyren Command Anti-Malware",
    company: "Cyren",
    city: "Herzliya",
    country: "Israel",
    continent: "Asia",
    timezone: "Asia/Jerusalem",
  },

  // ASIA
  {
    product: "Ahnlab",
    company: "AhnLab",
    city: "Seongnam (Pangyo)",
    country: "South Korea",
    continent: "Asia",
    timezone: "Asia/Seoul",
  },
  {
    product: "Estsoft ALYac",
    company: "ESTsoft",
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    timezone: "Asia/Seoul",
  },
  {
    product: "Inca v5",
    company: "INCA Internet (nProtect)",
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    timezone: "Asia/Seoul",
  },
  {
    product: "Inca V6 - PRIVÁT!",
    company: "INCA Internet (nProtect)",
    city: "Seoul",
    country: "South Korea",
    continent: "Asia",
    timezone: "Asia/Seoul",
  },
  {
    product: "CyRadar Endpoint Detection and Response",
    company: "CyRadar",
    city: "Hanoi",
    country: "Vietnam",
    continent: "Asia",
    timezone: "Asia/Ho_Chi_Minh",
  },
  {
    product: "Tencent PC Manager",
    company: "Tencent",
    city: "Shenzhen",
    country: "China",
    continent: "Asia",
    timezone: "Asia/Shanghai",
  },
  {
    product: "Tencent PC Manager –TAV",
    company: "Tencent",
    city: "Shenzhen",
    country: "China",
    continent: "Asia",
    timezone: "Asia/Shanghai",
  },
  {
    product: "Rising",
    company: "Rising",
    city: "Beijing",
    country: "China",
    continent: "Asia",
    timezone: "Asia/Shanghai",
  },
  {
    product: "Qianxin Enterprise Security Management System",
    company: "Qi'anxin (Qianxin)",
    city: "Beijing",
    country: "China",
    continent: "Asia",
    timezone: "Asia/Shanghai",
  },
  {
    product: "Qianxin Enterprise Security Management System v10",
    company: "Qi'anxin (Qianxin)",
    city: "Beijing",
    country: "China",
    continent: "Asia",
    timezone: "Asia/Shanghai",
  },
  {
    product: "eScan Internet Security Suite for Windows",
    company: "MicroWorld (eScan)",
    city: "Mumbai (Navi Mumbai)",
    country: "India",
    continent: "Asia",
    timezone: "Asia/Kolkata",
  },
  {
    product: "K7 Total Security",
    company: "K7 Computing",
    city: "Chennai",
    country: "India",
    continent: "Asia",
    timezone: "Asia/Kolkata",
  },
  {
    product: "Quick Heal Total Security",
    company: "Quick Heal",
    city: "Pune",
    country: "India",
    continent: "Asia",
    timezone: "Asia/Kolkata",
  },
  {
    product: "Quick Heal Seqrite Endpoint Security",
    company: "Quick Heal (Seqrite)",
    city: "Pune",
    country: "India",
    continent: "Asia",
    timezone: "Asia/Kolkata",
  },
  {
    product: "SecureAPlus Pro",
    company: "SecureAge Technology",
    city: "Singapore",
    country: "Singapore",
    continent: "Asia",
    timezone: "Asia/Singapore",
  },

  // AMERICA
  {
    product: "Fortinet FortiClient",
    company: "Fortinet",
    city: "Sunnyvale, CA",
    country: "United States",
    continent: "America",
    timezone: "America/Los_Angeles",
  },
  {
    product: "FireEye",
    company: "Mandiant / FireEye",
    city: "Milpitas, CA",
    country: "United States",
    continent: "America",
    timezone: "America/Los_Angeles",
  },
  {
    product: "SentinelOne",
    company: "SentinelOne",
    city: "Mountain View, CA",
    country: "United States",
    continent: "America",
    timezone: "America/Los_Angeles",
  },
  {
    product: "PC Pitstop PC Matic Home Security",
    company: "PC Matic",
    city: "Myrtle Beach, SC",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "ThreatTrack VIPRE Advanced Security",
    company: "VIPRE (ThreatTrack)",
    city: "Clearwater, FL",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "ThreatTrack VIPRE Advanced Security (Private Product)",
    company: "VIPRE (ThreatTrack)",
    city: "Clearwater, FL",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "TOTAL DEFENSE INTERNET SECURITY",
    company: "Total Defense",
    city: "Islandia/Hauppauge, NY",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "TOTAL DEFENSE PREMIUM",
    company: "Total Defense",
    city: "Islandia/Hauppauge, NY",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "TOTAL DEFENSE UNLIMITED",
    company: "Total Defense",
    city: "Islandia/Hauppauge, NY",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },
  {
    product: "WATCHDOG",
    company: "Watchdog Development",
    city: "Logan, UT",
    country: "United States",
    continent: "America",
    timezone: "America/Denver",
  },
  {
    product: "COMPUCLEVER ANTIVIRUS PLUS",
    company: "CompuClever Systems",
    city: "Victoria, BC",
    country: "Canada",
    continent: "America",
    timezone: "America/Vancouver",
  },
  {
    product: "Faronics ANTI-VIRUS TRUSTED Threat Protection",
    company: "Faronics",
    city: "Vancouver, BC",
    country: "Canada",
    continent: "America",
    timezone: "America/Vancouver",
  },
  {
    product: "Comodo",
    company: "Comodo Security Solutions",
    city: "Clifton, NJ",
    country: "United States",
    continent: "America",
    timezone: "America/New_York",
  },

  // PACIFIC
  {
    product: "Emsisoft Anti-Malware",
    company: "Emsisoft",
    city: "Nelson",
    country: "New Zealand",
    continent: "Pacific",
    timezone: "Pacific/Auckland",
  },

  // UK vendors (grouped under Europe/London)
  {
    product: "PC Protect",
    company: "Total Security Limited (Protected.net)",
    city: "Fareham, Hampshire",
    country: "United Kingdom",
    continent: "Europe",
    timezone: "Europe/London",
  },
  {
    product: "Scanguard",
    company: "Total Security Limited (Protected.net)",
    city: "Fareham, Hampshire",
    country: "United Kingdom",
    continent: "Europe",
    timezone: "Europe/London",
  },
  {
    product: "Total Av",
    company: "Total Security Limited (Protected.net)",
    city: "Fareham, Hampshire",
    country: "United Kingdom",
    continent: "Europe",
    timezone: "Europe/London",
  },

  // DENMARK
  {
    product: "Heimdal Thor Premium",
    company: "Heimdal",
    city: "Copenhagen",
    country: "Denmark",
    continent: "Europe",
    timezone: "Europe/Copenhagen",
  },
] as const;
